from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
import matplotlib.pyplot as plt
import os

plt.style.use("seaborn-v0_8-dark-palette")

# Define colors
CORPORATE_BLUE = RGBColor(0, 51, 102)
WHITE = RGBColor(255, 255, 255)
DARK_TEXT = RGBColor(40, 40, 40)

def add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    width, height = prs.slide_width, prs.slide_height

    # Blue background
    shape = slide.shapes.add_shape(
        MSO_AUTO_SHAPE_TYPE.RECTANGLE, 0, 0, width, height
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = CORPORATE_BLUE
    shape.line.fill.background()

    # Title
    title_box = slide.shapes.add_textbox(Inches(1), Inches(2), width - Inches(2), Inches(1))
    title_tf = title_box.text_frame
    p = title_tf.add_paragraph()
    p.text = title
    p.font.size = Pt(40)
    p.font.bold = True
    p.font.color.rgb = WHITE

    # Subtitle
    subtitle_box = slide.shapes.add_textbox(Inches(1), Inches(3), width - Inches(2), Inches(1))
    subtitle_tf = subtitle_box.text_frame
    p = subtitle_tf.add_paragraph()
    p.text = subtitle
    p.font.size = Pt(24)
    p.font.color.rgb = WHITE

def add_summary_slide(prs, summary):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    width = prs.slide_width

    # Title
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), width, Inches(1))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = "Executive Summary"
    p.font.size = Pt(32)
    p.font.bold = True
    p.font.color.rgb = CORPORATE_BLUE

    # Summary card
    card = slide.shapes.add_shape(
        MSO_AUTO_SHAPE_TYPE.RECTANGLE, Inches(0.5), Inches(1.5), width - Inches(1), Inches(4.5)
    )
    card.fill.solid()
    card.fill.fore_color.rgb = WHITE
    card.line.color.rgb = CORPORATE_BLUE

    text_frame = card.text_frame
    text_frame.word_wrap = True
    text_frame.margin_bottom = 0
    text_frame.margin_top = 0

    p = text_frame.paragraphs[0]
    p.text = summary.strip()
    p.font.size = Pt(18)
    p.font.color.rgb = DARK_TEXT

def add_chart_slide(prs, title, chart_path):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank

    # Title
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(0.8))
    title_tf = title_box.text_frame
    p = title_tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.color.rgb = CORPORATE_BLUE

    # Chart
    slide.shapes.add_picture(chart_path, Inches(1), Inches(1.5), width=Inches(7.5))

def create_ppt(metrics, summary, monthly_df=None):
    prs = Presentation()

    # --- Slide 1: Title ---
    add_title_slide(prs, "📘 Q2 Board Meeting Report", "Generated by AI Board Slide Generator")

    # --- Slide 2: Executive Summary ---
    add_summary_slide(prs, summary)

    if monthly_df is not None:
        os.makedirs("assets", exist_ok=True)

        # Revenue
        plt.figure(figsize=(7, 4))
        plt.plot(monthly_df['Month'], monthly_df['Revenue'], marker='o', linewidth=2.5)
        plt.title("Monthly Revenue")
        plt.xlabel("Month")
        plt.ylabel("Revenue")
        plt.grid(True)
        plt.tight_layout()
        path = "assets/revenue_chart.png"
        plt.savefig(path)
        plt.close()
        add_chart_slide(prs, "📈 Revenue Trend", path)

        # Cost
        plt.figure(figsize=(7, 4))
        plt.bar(monthly_df['Month'], monthly_df['Cost'], color='#1f77b4')
        plt.title("Monthly Costs")
        plt.xlabel("Month")
        plt.ylabel("Cost")
        plt.grid(axis='y')
        plt.tight_layout()
        path = "assets/cost_chart.png"
        plt.savefig(path)
        plt.close()
        add_chart_slide(prs, "💸 Cost Breakdown", path)

        # Churn
        plt.figure(figsize=(7, 4))
        plt.plot(monthly_df['Month'], monthly_df['Churn'], marker='x', linestyle='--', color='crimson')
        plt.title("Customer Churn Rate")
        plt.xlabel("Month")
        plt.ylabel("Churn (%)")
        plt.grid(True)
        plt.tight_layout()
        path = "assets/churn_chart.png"
        plt.savefig(path)
        plt.close()
        add_chart_slide(prs, "📉 Churn Trend", path)

    # --- Final Slide: Thanks ---
    add_title_slide(prs, "🙏 Thank You", "Questions? We’re happy to answer.")

    output_path = "Board_Meeting_Slides.pptx"
    prs.save(output_path)
    return output_path
